DROP DATABASE IF EXISTS bestself;
CREATE DATABASE bestself;

\c bestself;

CREATE TABLE USERS(
	user_id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(24) UNIQUE NOT NULL,
	password VARCHAR(70) NOT NULL,
	phone_number VARCHAR(16),
	name VARCHAR(40)
);

CREATE TABLE FEEDBACK(
	user_id INTEGER NOT NULL,
	comment VARCHAR(2000)
)
